### ISSUE TITLE
 Specs satisfying the `flutter_twitter (from `.symlinks/plugins/flutter_twitter/ios`)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by willladislaw** [roughike/flutter_twitter_login#26]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
flutter: 0
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_twitter
      - Flutter
      - connectivity
      - flutter_web_view
      - image_picker
      - path_provider

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `flutter_twitter` from `.symlinks/plugins/flutter_twitter/ios`
    -> Fetching podspec for `flutter_web_view` from `.symlinks/plugins/flutter_web_view/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "flutter_twitter":
      In Podfile:
        flutter_twitter (from `.symlinks/plugins/flutter_twitter/ios`)

    Specs satisfying the `flutter_twitter (from `.symlinks/plugins/flutter_twitter/ios`)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 11 Pro Max.

version:   flutter_twitter: ^1.1.3

Info.Plist 

	<key>CFBundleURLTypes</key>
    <array>
      <dict>
        <key>CFBundleURLSchemes</key>
        <array>
          <string>twitterkit-HPjTlQ.....</string>
        </array>
      </dict>
    </array>
    <key>LSApplicationQueriesSchemes</key>
    <array>
        <string>twitter</string>
        <string>twitterauth</string>
    </array>

**Comment by dmakwt** [comment]
Did you find solution? because I have same issue.

**Comment by willladislaw** [comment]
I'm waiting for a response.

**Comment by willladislaw** [comment]
> Did you find solution? because I have same issue.

The lack response leads me to think this plugin is no longer maintained and is out of date.

**Comment by willladislaw** [comment]
> Did you find solution? because I have same issue.

Lack of commits leads me to think this plugin is no longer maintained and is now out of date.

**Comment by dharialenezi** [comment]
Yes, maybe we should found another one or  make one

**Comment by willladislaw** [comment]
I have a moved on to something else for now.  If you find anything do post.

**Comment by scnctech** [comment]
I'm having the same issue here...  have you found any solutions? (works fine on android but i get the same error on iOS).

**Comment by scnctech** [comment]
So I was looking at the code and they ask for a minimun deployment target of iOS 10.1...
If you set the target to 10.1 it works fine!

**Comment by dannyhyatt** [comment]
@scnctech Disclaimer: I don't have a Mac, I use codemagic.io for builds. I've tried changing the target in the AppFrameworkInfo.plist to this

```
<key>MinimumOSVersion</key>
<string>12.0</string>
```

And I've also tried adding this line to Release.xcconfig:

`IPHONEOS_DEPLOYMENT_TARGET = 11.0`

Could you tell me how you changed the version?

**Comment by scnctech** [comment]
@dannyhyatt So I did it through XCode on a mac. There is a setting in the app properties to set the minimun deployment target and it has a dropdown menu to choose one. I wouldn't know how to do it through a file, sorry.

**Comment by canthelou-xyz** [comment]
Try adding this line in Podfile
platform :ios, '10.0'

**Comment by NimaSoroush** [comment]
Try add/uncomment this line in Podfile

```
platform :ios, '11.0'
```
